version: 0.2
phases: 
  install:
    commands:
      - echo installing node 12...
      - curl -sL https://deb/nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_builds:
    commands:
      - echo installing dependecies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-direction: dist











